// users
export const UPDATE_CURRENT_USER_INFO = "UPDATE_CURRENT_USER_INFO";
export const UPDATE_USER = "UPDATE_USER";
export const REMOVE_CONNECTION = "REMOVE_CONNECTION";
export const ADD_CONNECTION = "ADD_CONNECTION";
// dialog
export const ADD_ERROR_MESSAGE = "ADD_ERROR_MESSAGE";
export const ADD_SUCCESS_MESSAGE = "ADD_SUCCESS_MESSAGE";
export const ADD_INFO_MESSAGE = "ADD_INFO_MESSAGE";
export const SET_LOADING = "SET_LOADING";
export const CLEAR_DIALOG = "CLEAR_DIALOG";
// thread
export const ADD_THREAD = "ADD_THREAD";
export const EDIT_THREAD = "EDIT_THREAD";
export const REMOVE_THREAD = "REMOVE_THREAD";
export const ADD_REACTION = "ADD_THREAD_REACTION";
export const REMOVE_REACTION = "REMOVE_THREAD_REACTION";
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
// feed
export const UPDATE_FEED = "UPDATE_FEED";
export const SET_FEED_QUERY = "SET_FEED_QUERY";
export const SET_LAST_BUCKET_REACHED = "SET_LAST_BUCKET_REACHED";
// session
export const SET_IS_LOGGED_IN = "SET_IS_LOGGED_IN";
