export const UPDATE_CURRENT_USER_INFO = "UPDATE_CURRENT_USER_INFO";
export const UPDATE_USER = "UPDATE_USER";
export const REMOVE_CONNECTION = "REMOVE_CONNECTION";
export const ADD_CONNECTION = "ADD_CONNECTION";
